### ISSUE TITLE
winros_init_workspace fails

### ISSUE THREAD

**Issue by ghost** [ros-windows/win_ros#47]
Hello,

when I try to initialize the Workspace under "C:\ws" the process aborts after a while with following error:

```
rosinstall.common.MultiProjectExeption: Error processing 'gtest' : [gtest] Checkout of http://googletest.googlecode.com/svn/tags/release-1.6.0 version none into C:\ws\src\gtest failed.
```

I checked the url and it says 404: not found.
Because the process fails, no CMakeLists.txt is build and the workspace is not valid. So I cannot run winros_make nor can I install other packages in the workspace.

Any ideas how to solve this issue?

**Comment by stonier** [comment]
Moved to [github](https://github.com/google/googletest). Just update your rosinstalls to point to that, i.e.

```
{'git': {'local-name': 'gtest', 'version': 'release-1.6.0', 'uri': 'https://github.com/google/googletest'}}
```

Updated the hydro branch rosinstalls for that in 9d967797.
